Repository ICS3U-Gallo/project-hangman, pull requests merged in 2018-10, with the labels that each got.

#87 Add word_is_solved tests to tests.py
  tests.py
Labels: 11b

#101 Refactor player_is_dead
  hangman.py
Labels: 10

#103 Show title screen
  hangman.py
Labels: 10

#113 Refactor get_guess
  hangman.py
Labels: 10

#114 Update tests.py; adding tests for display_letters
  tests.py
Labels: 10

#117 Display_word function
  hangman.py
Labels: 11b

#118 Rename display_word to get_blanked_word. Implement tests. (Group 3)
  hangman.py
  tests.py
Labels: 11c

#119 Add title screen.
  hangman.py
Labels: 11c

#120 Group 2 word is solved
  hangman.py
Labels: 10
